on:
  workflow_call:
    inputs:
      dist:
        description: "The Perl distro being tested"
        type: string
        required: true
      ref:
        description: "The ref of this reusable workflow"
        type: string
        required: true
      min-perl:
        description: "The minimum version of Perl to test with"
        type: string
        default: "5.10.1"
      with-threads:
        description: "If true, then latest Perl with threads enabled will be added to the matrix"
        type: boolean
        default: false
      apt-packages-for-author-tests:
        description: "Apt packages to install when running author tests as a string containing a whitespace-separated list of packages"
        type: string

jobs:
  build-release-tarball:
    name: Build release tarball
    runs-on: ubuntu-latest
    steps:
      - name: Check out Perl project repository
        uses: actions/checkout@v4

      - name: Check out workflow repository
        uses: actions/checkout@v4
        with:
          repository: houseabsolute/workflow-perl-dzil-ci
          ref: ${{ inputs.ref }}
          # We have to use `./` at the beginning of a `uses:` path, so putting it under `.git`
          # ensures that tools like `precious` ignore it.
          path: ./.git/.workflow-perl-dzil-ci

      - name: Set up Perl
        uses: ./.git/.workflow-perl-dzil-ci/.github/actions/set-up-perl
        with:
          perl-version: latest
          cache-prefix: build-and-author-tests
          cache-extra: bin

      - name: Install Dist::Zilla and Test::Harness
        run: cpm install --global Dist::Zilla Test::Harness

      - name: Generate list of author deps
        # Some of my distros have author deps under `inc::` that live in the same repo.
        run: dzil authordeps | grep -v '^inc::' > /tmp/dzil-authordeps.txt

      - name: Upload dzil authordeps artifact
        uses: actions/upload-artifact@v4
        with:
          name: dzil-authordeps.txt
          path: /tmp/dzil-authordeps.txt

      - name: Install author deps
        run: |
          cpm install --show-build-log-on-failure --global $(cat /tmp/dzil-authordeps.txt)

      - name: Build release tarball
        run: dzil build

      - name: Upload release tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.dist }}.tar.gz"
          path: "*.tar.gz"

  define-matrix:
    name: Define test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.define-matrix.outputs.matrix }}
    steps:
      - name: Check out workflow repository
        uses: actions/checkout@v4
        with:
          repository: houseabsolute/workflow-perl-dzil-ci
          ref: ${{ inputs.ref }}
          path: ./.git/.workflow-perl-dzil-ci

      - name: Define test matrix
        id: define-matrix
        run: |
          perl ./.git/.workflow-perl-dzil-ci/.github/workflows/define-test-matrix.pl "${{ inputs.min-perl }}" "${{ inputs.with-threads }}"

      - name: Show matrix
        run: |
          echo '${{ steps.define-matrix.outputs.matrix }}' | jq .

  author-tests:
    needs: build-release-tarball
    name: Author tests with Perl latest
    runs-on: ubuntu-latest
    steps:
      - name: Install extra apt packages
        run: |
          set -e
          set -x

          if [ -n "${{ inputs.apt-packages-for-author-tests }}" ]; then
              sudo apt-get update
              # This will turn newlines into spaces.
              packages="$(perl -E 'say join q{ }, split /\s+/, q{${{ inputs.apt-packages-for-author-tests }}}')"
              sudo apt-get --yes install $packages
          fi

      - name: Check out workflow repository
        uses: actions/checkout@v4
        with:
          repository: houseabsolute/workflow-perl-dzil-ci
          ref: ${{ inputs.ref }}
          path: ./.git/.workflow-perl-dzil-ci

      - name: Download and unpack release tarball
        uses: ./.git/.workflow-perl-dzil-ci/.github/actions/download-and-unpack-release-tarball
        with:
          dist: ${{ inputs.dist }}

      - name: Set up Perl
        uses: ./.git/.workflow-perl-dzil-ci/.github/actions/set-up-perl
        with:
          perl-version: latest
          cache-prefix: build-and-author-tests
          cache-extra: bin

      - name: Install mise
        run: |
          set -e
          set -x

          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install aspell
        run: |
          set -e
          set -x

          sudo apt-get -y update
          sudo apt-get -y install aspell

      - name: Install module deps
        run: |
          cpm install --show-build-log-on-failure --global --with-all --cpanfile ./cpanfile

      - name: Run Makefile.PL and make
        run: |
          perl Makefile.PL
          make -j 24

      - name: Run tests
        run: |
          AUTOMATED_TESTING=1 \
              AUTHOR_TESTING=1 \
              EXTENDED_TESTING=1 \
              RELEASE_TESTING=1 \
              mise exec -- prove -br -j 24 t/ xt/

  test-matrix:
    needs:
      - build-release-tarball
      - define-matrix
    name: ${{ matrix.os-and-perl.name }} with Perl ${{ matrix.os-and-perl.perl-version }}
    runs-on: ${{ matrix.os-and-perl.runs-on }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}

    steps:
      - name: Check out workflow repository
        uses: actions/checkout@v4
        with:
          repository: houseabsolute/workflow-perl-dzil-ci
          ref: ${{ inputs.ref }}
          path: ./.git/.workflow-perl-dzil-ci

      - name: Download and unpack release tarball
        uses: ./.git/.workflow-perl-dzil-ci/.github/actions/download-and-unpack-release-tarball
        with:
          dist: ${{ inputs.dist }}

      - name: Set up Perl
        uses: ./.git/.workflow-perl-dzil-ci/.github/actions/set-up-perl
        with:
          perl-version: ${{ matrix.os-and-perl.perl-version }}
          multi-thread: ${{ matrix.os-and-perl.multi-thread }}
          cache-prefix: test-matrix
      - name: Install module deps
        # If we use bash on windows, cpm blows up in weird ways from missing prereqs.
        run: |
          cpm install --show-build-log-on-failure --global --cpanfile ./cpanfile

      - name: Run Makefile.PL and make
        run: |
          perl Makefile.PL
          ls
          make -j 24

      - name: Run tests
        # If we use bash on Windows we get an error that prove is not in the $PATH.
        run: |
          prove -br -j 24 t/
